### ISSUE TITLE
Any chance for an executable release?

### ISSUE THREAD

**Issue by andreyuv** [m2jean/ToothTray#1]
Hi,

I found this repo by googling and from the description it sounds like you managed to implement something workable. Any chance you could upload a compiled exe as a release? I don't know enough about windows programming to compile it myself.

Thank you for your time reading this.

**Comment by m2jean** [comment]
Haven't tested on any computer other than my own. Let me know if it works.
Release page: https://github.com/m2jean/ToothTray/releases/tag/0.1

**Comment by andreyuv** [comment]
Thank you very much for your help. I tested it and it works great on my computer.
The only problem is Windows Defender flags it as a trojan. It's obviously a false positive ([on virustotal no other antiviruses report any problems](https://www.virustotal.com/gui/file/cfe25f5fbb4b6be62088fc8fb7ca60539ca4a6520f77a8472a2599b90e3c5dad?nocache=1)).

Thanks again!
