### ISSUE TITLE
Command line version for scripting/macros?

### ISSUE THREAD

**Issue by mihalski** [m2jean/ToothTray#5]
I've been searching for a way to connect Bluetooth audio devices using macros/scripts and this seems to be by FAR the closest implementation of such a utility. Thank you very much for your contribution!

Is there any chance you would consider adding the ability to connect to a Bluetooth audio device by providing its name (or another applicable identifier) as a command line argument?

Thank you once again for your work.

**Comment by m2jean** [comment]
Hi @mihalski, currently I don't have a plan to add command line support, but if you are able to compile the project, it should be trivial to add a command line interface. Use the [BluetoothAudioDeviceEnumerator](https://github.com/m2jean/ToothTray/blob/master/ToothTray/BluetoothAudioDevices.h#L42) to get all the connectors, and then you can get their device names or change connection states.

**Comment by shunf4** [comment]
My fork is a CLI version: https://github.com/shunf4/ToothTrayCli

**Comment by meloman27** [comment]
> My fork is a CLI version: https://github.com/shunf4/ToothTrayCli

Hello, your program works fine with command line, thanks! Could you make an x32 version of the program?

**Comment by shunf4** [comment]
> > My fork is a CLI version: https://github.com/shunf4/ToothTrayCli
> 
> Hello, your program works fine with command line, thanks! Could you make an x32 version of the program?

@meloman27 try the latest pre-release.

**Comment by meloman27** [comment]
> try the latest pre-release.

Wow!!! Thank you very mutch! Everything works fine, everything works on Windows 10 32 Bit too! It was required only to install Microsoft Visual C ++ 2015 Redistributable, as I needed a file VCRгntime140.dll
